apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-mbooking-ms-hpa
  namespace: prod
  labels:
    env: prod
    app: mbooking-ms
    layer: frontend
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: prod-mbooking-ms-deployment
  targetCPUUtilizationPercentage: 80