apiVersion: v1
kind: ConfigMap
metadata:
  name: preprod-mbooking-ms-application-config
  namespace: preprod
  labels:
    env: preprod
    app: mbooking-ms
    layer: frontend
data:
  application.properties: |-