apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: preprod-mbooking-ms-hpa
  namespace: preprod
  labels:
    env: preprod
    app: mbooking-ms
    layer: frontend
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: preprod-mbooking-ms-deployment
  targetCPUUtilizationPercentage: 80